<!DOCTYPE html>
<html lang="en">
<head>
    <!-- META -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Gameforest - Responsive Gaming HTML Theme</title>

    <!-- FAVICON -->
    <link rel="shortcut icon" href="img/insidific.png">

    <!-- CORE CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

</head>